import { Alert, Compound, WatchlistEntry, WatchlistHighlight, UpdateCard } from "@/types";

export const mockAlerts: Alert[] = [
  {
    id: "1",
    title: "4 New Substances Designated as Shitei Yakubutsu",
    severity: "critical",
    category: "designated_substance",
    status: "official_confirmed",
    source_tier: 1,
    confidence_level: "official",
    published_at: "2026-03-04T09:00:00Z",
    effective_at: "2026-04-01T00:00:00Z",
    summary_what: "MHLW officially designated 4 new synthetic cannabinoids as Designated Substances (Shitei Yakubutsu), effective April 1, 2026.",
    summary_why: "Products containing these substances will become illegal to manufacture, sell, possess, or use.",
    summary_who: "All CBD/cannabinoid product manufacturers, importers, retailers, and consumers in Japan.",
    compounds: ["THCP", "HHCP", "HHCH", "HHC-O"],
    product_forms: ["oil", "vape", "gummy", "powder"],
    agencies: ["MHLW"],
    importance_score: 95,
    diff_before: "Designated Substances List: 2,456 substances",
    diff_after: "Designated Substances List: 2,460 substances (+4 cannabinoids)",
    diff_type: "status",
    primary_source_url: "https://www.mhlw.go.jp",
    created_at: "2026-03-04T10:00:00Z",
  },
  {
    id: "2",
    title: "THC Residual Limit Enforcement Now Active",
    severity: "critical",
    category: "threshold",
    status: "official_confirmed",
    source_tier: 1,
    confidence_level: "official",
    published_at: "2025-12-12T00:00:00Z",
    effective_at: "2025-12-12T00:00:00Z",
    summary_what: "THC residual limit values for cannabis-derived products are now enforceable. Products exceeding limits face regulatory action.",
    summary_why: "Japan now has the world's strictest THC residual standards. Non-compliant products must be recalled.",
    summary_who: "All importers and sellers of CBD/cannabinoid products in Japan.",
    compounds: ["THC", "CBD", "CBN", "CBG"],
    product_forms: ["oil", "food", "cosmetics", "vape"],
    agencies: ["MHLW", "NCD"],
    importance_score: 92,
    diff_before: "THC limit: 0.3% (industry self-regulation)",
    diff_after: "THC limit: Not Detected (ND) for most product categories",
    diff_type: "threshold",
    primary_source_url: "https://www.mhlw.go.jp",
    created_at: "2025-12-12T01:00:00Z",
  },
  {
    id: "3",
    title: "CBN Regulation Under Review by MHLW Committee",
    severity: "high",
    category: "regulation",
    status: "pending",
    source_tier: 2,
    confidence_level: "unverified",
    published_at: "2026-02-15T09:00:00Z",
    effective_at: null,
    summary_what: "Industry reports suggest CBN may be added to the designated substances list. MHLW committee reviewing evidence.",
    summary_why: "If designated, all CBN products (oils, gummies, vapes) would become illegal in Japan.",
    summary_who: "CBN product manufacturers, retailers, and consumers.",
    compounds: ["CBN"],
    product_forms: ["oil", "gummy", "vape", "capsule"],
    agencies: ["MHLW"],
    importance_score: 78,
    diff_before: "CBN: Not regulated (legal)",
    diff_after: "CBN: Under review for designation",
    diff_type: "status",
    created_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "4",
    title: "Cannabis Control Act: Use Crime Now Enforceable",
    severity: "high",
    category: "enforcement",
    status: "official_confirmed",
    source_tier: 1,
    confidence_level: "official",
    published_at: "2025-03-01T00:00:00Z",
    effective_at: "2025-03-01T00:00:00Z",
    summary_what: "The revised Cannabis Control Act now criminalizes the 'use' of cannabis, not just possession.",
    summary_why: "Previously only possession was illegal. Now consuming cannabis products is also a criminal offense.",
    summary_who: "All individuals in Japan. Particularly relevant for those using imported cannabis-derived products.",
    compounds: ["THC"],
    product_forms: [],
    agencies: ["MHLW", "NPA"],
    importance_score: 88,
    diff_before: "Cannabis Control Act: Possession = illegal, Use = not criminalized",
    diff_after: "Cannabis Control Act: Possession = illegal, Use = illegal (criminal penalty)",
    diff_type: "scope",
    primary_source_url: "https://www.mhlw.go.jp",
    created_at: "2025-03-01T01:00:00Z",
  },
  {
    id: "5",
    title: "Public Comment Period Open: CBD Import Procedure Changes",
    severity: "medium",
    category: "regulation",
    status: "verified",
    source_tier: 1,
    confidence_level: "verified",
    published_at: "2026-02-20T09:00:00Z",
    effective_at: "2026-03-20T23:59:00Z",
    summary_what: "e-Gov public comment period opened for proposed changes to CBD product import verification procedures.",
    summary_why: "New requirements may increase documentation burden for importers.",
    summary_who: "CBD product importers and distributors.",
    compounds: ["CBD"],
    product_forms: ["oil", "powder", "cosmetics"],
    agencies: ["NCD"],
    importance_score: 62,
    diff_before: "Import verification: Standard non-correspondence form",
    diff_after: "Import verification: Enhanced form + LOQ/LOD documentation required",
    diff_type: "scope",
    created_at: "2026-02-20T10:00:00Z",
  },
  {
    id: "6",
    title: "Tokyo Metropolitan Government Product Survey Results",
    severity: "medium",
    category: "enforcement",
    status: "verified",
    source_tier: 2,
    confidence_level: "verified",
    published_at: "2026-01-10T09:00:00Z",
    effective_at: null,
    summary_what: "Tokyo prefectural survey found 3 products exceeding THC residual limits. Products ordered recalled.",
    summary_why: "Enforcement of new THC limits is actively happening at the prefectural level.",
    summary_who: "Retailers in Tokyo area. Consumers should check product batch numbers.",
    compounds: ["THC", "CBD"],
    product_forms: ["oil", "gummy"],
    agencies: ["Tokyo Metropolitan Government"],
    importance_score: 55,
    diff_before: "",
    diff_after: "",
    diff_type: "status",
    created_at: "2026-01-10T10:00:00Z",
  },
];

export const mockCompounds: Compound[] = [
  {
    id: "1",
    name: "CBD",
    aliases: ["Cannabidiol", "カンナビジオール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "safe",
    legal_status_updated_at: "2025-12-12T00:00:00Z",
    effects_summary: "Legal with conditions. THC residual limits apply. Must comply with import verification procedures.",
  },
  {
    id: "2",
    name: "CBN",
    aliases: ["Cannabinol", "カンナビノール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "under_review",
    risk_level: "high",
    legal_status_updated_at: "2026-02-15T00:00:00Z",
    effects_summary: "Currently legal but under regulatory review. MHLW committee has discussed potential designation. High risk of status change.",
  },
  {
    id: "3",
    name: "CBG",
    aliases: ["Cannabigerol", "カンナビゲロール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "safe",
    legal_status_updated_at: "2025-12-12T00:00:00Z",
    effects_summary: "Legal with conditions. Subject to same THC residual limits as CBD products.",
  },
  {
    id: "4",
    name: "CBC",
    aliases: ["Cannabichromene", "カンナビクロメン"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "unknown",
    risk_level: "medium",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "Not explicitly regulated. Limited market presence in Japan. Monitor for regulatory changes.",
  },
  {
    id: "5",
    name: "CBL",
    aliases: ["Cannabicyclol", "カンナビシクロール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "unknown",
    risk_level: "low",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "Not regulated. Minimal commercial availability in Japan.",
  },
  {
    id: "6",
    name: "THC",
    aliases: ["Tetrahydrocannabinol", "テトラヒドロカンナビノール", "Δ9-THC", "delta-9 THC"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "2025-03-01T00:00:00Z",
    effects_summary: "Illegal. Controlled under the Cannabis Control Act and Narcotics and Psychotropics Control Act. Use crime now enforceable.",
  },
  {
    id: "7",
    name: "THCV",
    aliases: ["Tetrahydrocannabivarin", "テトラヒドロカンナビバリン"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "unknown",
    risk_level: "medium",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "Regulatory status unclear. Structurally related to THC. Monitor closely.",
  },
  {
    id: "8",
    name: "THCP",
    aliases: ["Tetrahydrocannabiphorol", "テトラヒドロカンナビフォロール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "promulgated",
    risk_level: "illegal",
    legal_status_updated_at: "2026-03-04T00:00:00Z",
    effects_summary: "Designated as Shitei Yakubutsu. Effective April 1, 2026. All products illegal.",
  },
  {
    id: "9",
    name: "HHC",
    aliases: ["Hexahydrocannabinol", "ヘキサヒドロカンナビノール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "2023-03-01T00:00:00Z",
    effects_summary: "Designated Substance since March 2023. Manufacturing, sale, possession, and use are illegal.",
  },
  {
    id: "10",
    name: "HHCH",
    aliases: ["Hexahydrocannabihexol"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "promulgated",
    risk_level: "illegal",
    legal_status_updated_at: "2026-03-04T00:00:00Z",
    effects_summary: "Designated as Shitei Yakubutsu. Effective April 1, 2026.",
  },
  {
    id: "11",
    name: "HHCP",
    aliases: ["Hexahydrocannabiphorol"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "promulgated",
    risk_level: "illegal",
    legal_status_updated_at: "2026-03-04T00:00:00Z",
    effects_summary: "Designated as Shitei Yakubutsu. Effective April 1, 2026.",
  },
  {
    id: "12",
    name: "H4CBD",
    aliases: ["Hexahydrocannabidiol"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "unknown",
    risk_level: "high",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "Not yet designated but structurally similar to regulated compounds. High risk of future regulation.",
  },
  // ── Psychedelics / Tryptamines ──
  {
    id: "13",
    name: "1P-LSD",
    aliases: ["1-Propionyl-LSD", "1プロピオニルLSD"],
    chemical_family: "Lysergamide",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "2024-07-01T00:00:00Z",
    effects_summary: "指定薬物として規制済。LSDプロドラッグ。製造・販売・所持・使用すべて違法。",
  },
  {
    id: "14",
    name: "1cP-LSD",
    aliases: ["1-Cyclopropionyl-LSD"],
    chemical_family: "Lysergamide",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "2024-07-01T00:00:00Z",
    effects_summary: "指定薬物。包括指定により1P-LSDと同時に規制。",
  },
  {
    id: "15",
    name: "1V-LSD",
    aliases: ["1-Valeroyl-LSD", "Valerie"],
    chemical_family: "Lysergamide",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "unknown",
    risk_level: "high",
    legal_status_updated_at: "2025-09-01T00:00:00Z",
    effects_summary: "包括指定の対象外との見解もあるが、構造類似で規制リスク高。流通は限定的。",
  },
  {
    id: "16",
    name: "1D-LSD",
    aliases: ["1-(1,2-Dimethylcyclobutane-1-carbonyl)-LSD"],
    chemical_family: "Lysergamide",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "unknown",
    risk_level: "medium",
    legal_status_updated_at: "2025-11-01T00:00:00Z",
    effects_summary: "最新世代のLSDアナログ。日本での規制状況は未確認。ドイツでは2024年に規制。",
  },
  {
    id: "17",
    name: "Psilocybin",
    aliases: ["サイロシビン", "シロシビン", "4-PO-DMT"],
    chemical_family: "Tryptamine",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "1971-04-01T00:00:00Z",
    effects_summary: "麻薬及び向精神薬取締法で規制。マジックマッシュルームの主成分。所持・使用違法。",
  },
  {
    id: "18",
    name: "Psilocin",
    aliases: ["サイロシン", "シロシン", "4-HO-DMT"],
    chemical_family: "Tryptamine",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "1971-04-01T00:00:00Z",
    effects_summary: "サイロシビンの活性代謝物。同様に麻薬指定。",
  },
  {
    id: "19",
    name: "4-AcO-DMT",
    aliases: ["Psilacetin", "O-Acetylpsilocin", "合成シロシビン"],
    chemical_family: "Tryptamine",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "2015-04-01T00:00:00Z",
    effects_summary: "指定薬物。サイロシビンのプロドラッグとして合成。製造・所持違法。",
  },
  {
    id: "20",
    name: "Amanita muscaria",
    aliases: ["ベニテングタケ", "Fly Agaric", "アマニタ"],
    chemical_family: "Isoxazole",
    natural_or_synthetic: "natural",
    legal_status_japan: "unknown",
    risk_level: "low",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "規制対象外。ムシモール・イボテン酸を含む。食用キノコとして規制なし。一部でマイクロドーズ利用。",
  },
  {
    id: "21",
    name: "Muscimol",
    aliases: ["ムシモール", "ムッシモール"],
    chemical_family: "Isoxazole",
    natural_or_synthetic: "natural",
    legal_status_japan: "unknown",
    risk_level: "low",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "ベニテングタケの主成分。現時点で規制対象外。GABA-A受容体作動薬。",
  },
  // ── Kratom / Mitragynine ──
  {
    id: "22",
    name: "Kratom",
    aliases: ["クラトム", "Mitragyna speciosa", "ミトラガイナ"],
    chemical_family: "Indole Alkaloid",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "safe",
    legal_status_updated_at: "2025-01-01T00:00:00Z",
    effects_summary: "日本では合法。食品として流通。ミトラギニン・7-ヒドロキシミトラギニンを含む。タイでは2021年に合法化。",
  },
  {
    id: "23",
    name: "Mitragynine",
    aliases: ["ミトラギニン"],
    chemical_family: "Indole Alkaloid",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "safe",
    legal_status_updated_at: "2025-01-01T00:00:00Z",
    effects_summary: "クラトムの主成分。日本では規制対象外。オピオイド受容体部分作動薬。",
  },
  // ── Phenethylamines ──
  {
    id: "24",
    name: "Mescaline",
    aliases: ["メスカリン", "3,4,5-TMP"],
    chemical_family: "Phenethylamine",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "1971-04-01T00:00:00Z",
    effects_summary: "麻薬指定。ペヨーテ・サンペドロカクタスの主成分。所持・使用違法。",
  },
  {
    id: "25",
    name: "San Pedro",
    aliases: ["サンペドロ", "Echinopsis pachanoi", "柱サボテン"],
    chemical_family: "Phenethylamine",
    natural_or_synthetic: "natural",
    legal_status_japan: "unknown",
    risk_level: "medium",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "植物自体は観賞用として入手可能。メスカリン抽出目的の所持は違法の可能性。グレーゾーン。",
  },
  // ── Novel substances ──
  {
    id: "26",
    name: "2-FDK",
    aliases: ["2-Fluorodeschloroketamine", "2-フルオロケタミン"],
    chemical_family: "Arylcyclohexylamine",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "unknown",
    risk_level: "medium",
    legal_status_updated_at: "2025-08-01T00:00:00Z",
    effects_summary: "ケタミン類似体。指定薬物リストに未掲載だが、包括指定の対象となる可能性。",
  },
  {
    id: "27",
    name: "Ketamine",
    aliases: ["ケタミン", "Ketalar"],
    chemical_family: "Arylcyclohexylamine",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "2007-01-01T00:00:00Z",
    effects_summary: "麻薬指定。医療用は処方可能。レクリエーション使用は違法。NMDA受容体拮抗薬。",
  },
  {
    id: "28",
    name: "DMT",
    aliases: ["N,N-DMT", "ジメチルトリプタミン", "Dimethyltryptamine"],
    chemical_family: "Tryptamine",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "1971-04-01T00:00:00Z",
    effects_summary: "麻薬指定。アヤワスカの主成分。内因性トリプタミン。所持・使用違法。",
  },
  {
    id: "29",
    name: "5-MeO-DMT",
    aliases: ["5メトキシDMT", "Toad Venom"],
    chemical_family: "Tryptamine",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "2015-04-01T00:00:00Z",
    effects_summary: "指定薬物。ヒキガエル毒に含有。極めて強力なセロトニン作動薬。",
  },
  {
    id: "30",
    name: "LSA",
    aliases: ["リゼルグ酸アミド", "Ergine", "Morning Glory"],
    chemical_family: "Lysergamide",
    natural_or_synthetic: "natural",
    legal_status_japan: "unknown",
    risk_level: "low",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "朝顔・ハワイアンウッドローズの種子に含有。植物自体は規制対象外。LSAそのものの法的位置づけは不明確。",
  },
  {
    id: "31",
    name: "MDMA",
    aliases: ["エクスタシー", "Molly", "3,4-MDMA"],
    chemical_family: "Phenethylamine",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "1991-01-01T00:00:00Z",
    effects_summary: "麻薬指定。セロトニン放出薬。海外ではPTSD治療薬として承認進行中。日本では所持・使用違法。",
  },
  {
    id: "32",
    name: "GHB",
    aliases: ["γ-ヒドロキシ酪酸", "Gamma-Hydroxybutyrate"],
    chemical_family: "GHB",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "2001-01-01T00:00:00Z",
    effects_summary: "麻薬指定。GABA-B受容体作動薬。ナルコレプシー治療薬としては医療用存在。",
  },
  {
    id: "33",
    name: "Salvinorin A",
    aliases: ["サルビノリンA", "Salvia divinorum"],
    chemical_family: "Terpenoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "2007-04-01T00:00:00Z",
    effects_summary: "指定薬物。サルビア・ディビノラムの主成分。κオピオイド受容体作動薬。",
  },
  {
    id: "34",
    name: "Kava",
    aliases: ["カバカバ", "Piper methysticum", "カヴァ"],
    chemical_family: "Kavalactone",
    natural_or_synthetic: "natural",
    legal_status_japan: "unknown",
    risk_level: "safe",
    legal_status_updated_at: "2025-01-01T00:00:00Z",
    effects_summary: "規制対象外。南太平洋の伝統飲料。GABA作動性。サプリメントとして流通。肝毒性に注意。",
  },
  {
    id: "35",
    name: "Phenibut",
    aliases: ["フェニバット", "β-Phenyl-GABA"],
    chemical_family: "GABA Analog",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "unknown",
    risk_level: "medium",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "日本では未規制だが医薬品成分の可能性。ロシアでは処方薬。GABA-B作動薬。依存性あり。",
  },
];

export const mockWatchlist: WatchlistEntry[] = [
  {
    id: "w1",
    user_id: "user1",
    entity_type: "compound",
    entity_id: "1",
    entity_name: "CBD",
    created_at: "2026-01-01T00:00:00Z",
    notification_enabled: true,
  },
  {
    id: "w2",
    user_id: "user1",
    entity_type: "compound",
    entity_id: "2",
    entity_name: "CBN",
    created_at: "2026-01-15T00:00:00Z",
    notification_enabled: true,
  },
  {
    id: "w3",
    user_id: "user1",
    entity_type: "compound",
    entity_id: "6",
    entity_name: "THC",
    created_at: "2026-02-01T00:00:00Z",
    notification_enabled: true,
  },
  {
    id: "w4",
    user_id: "user1",
    entity_type: "product_form",
    entity_id: "pf1",
    entity_name: "CBD Oil",
    created_at: "2026-02-10T00:00:00Z",
    notification_enabled: false,
  },
];

export const mockWatchlistHighlights: WatchlistHighlight[] = [
  {
    entity_type: "compound",
    entity_name: "CBN",
    change: "Unknown → Under Review",
    changed_at: "2026-02-15T09:00:00Z",
  },
  {
    entity_type: "compound",
    entity_name: "CBD",
    change: "THC residual limits now enforced",
    changed_at: "2025-12-12T00:00:00Z",
  },
];

export const mockUpdateCards: UpdateCard[] = [
  {
    id: "u1",
    type: "emergency",
    title: "4 New Designated Substances",
    date: "2026-03-04",
    impact: ["THCP", "HHCP", "HHCH", "HHC-O"],
    alert_id: "1",
  },
  {
    id: "u2",
    type: "warning",
    title: "CBN Under Regulatory Review",
    date: "2026-02-15",
    impact: ["oil", "gummy", "vape"],
    alert_id: "3",
  },
  {
    id: "u3",
    type: "update",
    title: "CBD Import Procedure Changes",
    date: "2026-02-20",
    impact: ["oil", "powder", "cosmetics"],
    alert_id: "5",
  },
];
