import { Alert, Compound, WatchlistEntry, WatchlistHighlight, UpdateCard } from "@/types";

export const mockAlerts: Alert[] = [
  {
    id: "1",
    title: "4 New Substances Designated as Shitei Yakubutsu",
    severity: "critical",
    category: "designated_substance",
    status: "official_confirmed",
    source_tier: 1,
    confidence_level: "official",
    published_at: "2026-03-04T09:00:00Z",
    effective_at: "2026-04-01T00:00:00Z",
    summary_what: "MHLW officially designated 4 new synthetic cannabinoids as Designated Substances (Shitei Yakubutsu), effective April 1, 2026.",
    summary_why: "Products containing these substances will become illegal to manufacture, sell, possess, or use.",
    summary_who: "All CBD/cannabinoid product manufacturers, importers, retailers, and consumers in Japan.",
    compounds: ["THCP", "HHCP", "HHCH", "HHC-O"],
    product_forms: ["oil", "vape", "gummy", "powder"],
    agencies: ["MHLW"],
    importance_score: 95,
    diff_before: "Designated Substances List: 2,456 substances",
    diff_after: "Designated Substances List: 2,460 substances (+4 cannabinoids)",
    diff_type: "status",
    primary_source_url: "https://www.mhlw.go.jp",
    created_at: "2026-03-04T10:00:00Z",
  },
  {
    id: "2",
    title: "THC Residual Limit Enforcement Now Active",
    severity: "critical",
    category: "threshold",
    status: "official_confirmed",
    source_tier: 1,
    confidence_level: "official",
    published_at: "2025-12-12T00:00:00Z",
    effective_at: "2025-12-12T00:00:00Z",
    summary_what: "THC residual limit values for cannabis-derived products are now enforceable. Products exceeding limits face regulatory action.",
    summary_why: "Japan now has the world's strictest THC residual standards. Non-compliant products must be recalled.",
    summary_who: "All importers and sellers of CBD/cannabinoid products in Japan.",
    compounds: ["THC", "CBD", "CBN", "CBG"],
    product_forms: ["oil", "food", "cosmetics", "vape"],
    agencies: ["MHLW", "NCD"],
    importance_score: 92,
    diff_before: "THC limit: 0.3% (industry self-regulation)",
    diff_after: "THC limit: Not Detected (ND) for most product categories",
    diff_type: "threshold",
    primary_source_url: "https://www.mhlw.go.jp",
    created_at: "2025-12-12T01:00:00Z",
  },
  {
    id: "3",
    title: "CBN Regulation Under Review by MHLW Committee",
    severity: "high",
    category: "regulation",
    status: "pending",
    source_tier: 2,
    confidence_level: "unverified",
    published_at: "2026-02-15T09:00:00Z",
    effective_at: null,
    summary_what: "Industry reports suggest CBN may be added to the designated substances list. MHLW committee reviewing evidence.",
    summary_why: "If designated, all CBN products (oils, gummies, vapes) would become illegal in Japan.",
    summary_who: "CBN product manufacturers, retailers, and consumers.",
    compounds: ["CBN"],
    product_forms: ["oil", "gummy", "vape", "capsule"],
    agencies: ["MHLW"],
    importance_score: 78,
    diff_before: "CBN: Not regulated (legal)",
    diff_after: "CBN: Under review for designation",
    diff_type: "status",
    created_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "4",
    title: "Cannabis Control Act: Use Crime Now Enforceable",
    severity: "high",
    category: "enforcement",
    status: "official_confirmed",
    source_tier: 1,
    confidence_level: "official",
    published_at: "2025-03-01T00:00:00Z",
    effective_at: "2025-03-01T00:00:00Z",
    summary_what: "The revised Cannabis Control Act now criminalizes the 'use' of cannabis, not just possession.",
    summary_why: "Previously only possession was illegal. Now consuming cannabis products is also a criminal offense.",
    summary_who: "All individuals in Japan. Particularly relevant for those using imported cannabis-derived products.",
    compounds: ["THC"],
    product_forms: [],
    agencies: ["MHLW", "NPA"],
    importance_score: 88,
    diff_before: "Cannabis Control Act: Possession = illegal, Use = not criminalized",
    diff_after: "Cannabis Control Act: Possession = illegal, Use = illegal (criminal penalty)",
    diff_type: "scope",
    primary_source_url: "https://www.mhlw.go.jp",
    created_at: "2025-03-01T01:00:00Z",
  },
  {
    id: "5",
    title: "Public Comment Period Open: CBD Import Procedure Changes",
    severity: "medium",
    category: "regulation",
    status: "verified",
    source_tier: 1,
    confidence_level: "verified",
    published_at: "2026-02-20T09:00:00Z",
    effective_at: "2026-03-20T23:59:00Z",
    summary_what: "e-Gov public comment period opened for proposed changes to CBD product import verification procedures.",
    summary_why: "New requirements may increase documentation burden for importers.",
    summary_who: "CBD product importers and distributors.",
    compounds: ["CBD"],
    product_forms: ["oil", "powder", "cosmetics"],
    agencies: ["NCD"],
    importance_score: 62,
    diff_before: "Import verification: Standard non-correspondence form",
    diff_after: "Import verification: Enhanced form + LOQ/LOD documentation required",
    diff_type: "scope",
    created_at: "2026-02-20T10:00:00Z",
  },
  {
    id: "6",
    title: "Tokyo Metropolitan Government Product Survey Results",
    severity: "medium",
    category: "enforcement",
    status: "verified",
    source_tier: 2,
    confidence_level: "verified",
    published_at: "2026-01-10T09:00:00Z",
    effective_at: null,
    summary_what: "Tokyo prefectural survey found 3 products exceeding THC residual limits. Products ordered recalled.",
    summary_why: "Enforcement of new THC limits is actively happening at the prefectural level.",
    summary_who: "Retailers in Tokyo area. Consumers should check product batch numbers.",
    compounds: ["THC", "CBD"],
    product_forms: ["oil", "gummy"],
    agencies: ["Tokyo Metropolitan Government"],
    importance_score: 55,
    diff_before: "",
    diff_after: "",
    diff_type: "status",
    created_at: "2026-01-10T10:00:00Z",
  },
];

export const mockCompounds: Compound[] = [
  {
    id: "1",
    name: "CBD",
    aliases: ["Cannabidiol", "カンナビジオール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "safe",
    legal_status_updated_at: "2025-12-12T00:00:00Z",
    effects_summary: "Legal with conditions. THC residual limits apply. Must comply with import verification procedures.",
  },
  {
    id: "2",
    name: "CBN",
    aliases: ["Cannabinol", "カンナビノール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "under_review",
    risk_level: "high",
    legal_status_updated_at: "2026-02-15T00:00:00Z",
    effects_summary: "Currently legal but under regulatory review. MHLW committee has discussed potential designation. High risk of status change.",
  },
  {
    id: "3",
    name: "CBG",
    aliases: ["Cannabigerol", "カンナビゲロール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "safe",
    legal_status_updated_at: "2025-12-12T00:00:00Z",
    effects_summary: "Legal with conditions. Subject to same THC residual limits as CBD products.",
  },
  {
    id: "4",
    name: "CBC",
    aliases: ["Cannabichromene", "カンナビクロメン"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "unknown",
    risk_level: "medium",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "Not explicitly regulated. Limited market presence in Japan. Monitor for regulatory changes.",
  },
  {
    id: "5",
    name: "CBL",
    aliases: ["Cannabicyclol", "カンナビシクロール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "unknown",
    risk_level: "low",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "Not regulated. Minimal commercial availability in Japan.",
  },
  {
    id: "6",
    name: "THC",
    aliases: ["Tetrahydrocannabinol", "テトラヒドロカンナビノール", "Δ9-THC", "delta-9 THC"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "2025-03-01T00:00:00Z",
    effects_summary: "Illegal. Controlled under the Cannabis Control Act and Narcotics and Psychotropics Control Act. Use crime now enforceable.",
  },
  {
    id: "7",
    name: "THCV",
    aliases: ["Tetrahydrocannabivarin", "テトラヒドロカンナビバリン"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "natural",
    legal_status_japan: "unknown",
    risk_level: "medium",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "Regulatory status unclear. Structurally related to THC. Monitor closely.",
  },
  {
    id: "8",
    name: "THCP",
    aliases: ["Tetrahydrocannabiphorol", "テトラヒドロカンナビフォロール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "promulgated",
    risk_level: "illegal",
    legal_status_updated_at: "2026-03-04T00:00:00Z",
    effects_summary: "Designated as Shitei Yakubutsu. Effective April 1, 2026. All products illegal.",
  },
  {
    id: "9",
    name: "HHC",
    aliases: ["Hexahydrocannabinol", "ヘキサヒドロカンナビノール"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "effective",
    risk_level: "illegal",
    legal_status_updated_at: "2023-03-01T00:00:00Z",
    effects_summary: "Designated Substance since March 2023. Manufacturing, sale, possession, and use are illegal.",
  },
  {
    id: "10",
    name: "HHCH",
    aliases: ["Hexahydrocannabihexol"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "promulgated",
    risk_level: "illegal",
    legal_status_updated_at: "2026-03-04T00:00:00Z",
    effects_summary: "Designated as Shitei Yakubutsu. Effective April 1, 2026.",
  },
  {
    id: "11",
    name: "HHCP",
    aliases: ["Hexahydrocannabiphorol"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "promulgated",
    risk_level: "illegal",
    legal_status_updated_at: "2026-03-04T00:00:00Z",
    effects_summary: "Designated as Shitei Yakubutsu. Effective April 1, 2026.",
  },
  {
    id: "12",
    name: "H4CBD",
    aliases: ["Hexahydrocannabidiol"],
    chemical_family: "Cannabinoid",
    natural_or_synthetic: "synthetic",
    legal_status_japan: "unknown",
    risk_level: "high",
    legal_status_updated_at: "2025-06-01T00:00:00Z",
    effects_summary: "Not yet designated but structurally similar to regulated compounds. High risk of future regulation.",
  },
];

export const mockWatchlist: WatchlistEntry[] = [
  {
    id: "w1",
    user_id: "user1",
    entity_type: "compound",
    entity_id: "1",
    entity_name: "CBD",
    created_at: "2026-01-01T00:00:00Z",
    notification_enabled: true,
  },
  {
    id: "w2",
    user_id: "user1",
    entity_type: "compound",
    entity_id: "2",
    entity_name: "CBN",
    created_at: "2026-01-15T00:00:00Z",
    notification_enabled: true,
  },
  {
    id: "w3",
    user_id: "user1",
    entity_type: "compound",
    entity_id: "6",
    entity_name: "THC",
    created_at: "2026-02-01T00:00:00Z",
    notification_enabled: true,
  },
  {
    id: "w4",
    user_id: "user1",
    entity_type: "product_form",
    entity_id: "pf1",
    entity_name: "CBD Oil",
    created_at: "2026-02-10T00:00:00Z",
    notification_enabled: false,
  },
];

export const mockWatchlistHighlights: WatchlistHighlight[] = [
  {
    entity_type: "compound",
    entity_name: "CBN",
    change: "Unknown → Under Review",
    changed_at: "2026-02-15T09:00:00Z",
  },
  {
    entity_type: "compound",
    entity_name: "CBD",
    change: "THC residual limits now enforced",
    changed_at: "2025-12-12T00:00:00Z",
  },
];

export const mockUpdateCards: UpdateCard[] = [
  {
    id: "u1",
    type: "emergency",
    title: "4 New Designated Substances",
    date: "2026-03-04",
    impact: ["THCP", "HHCP", "HHCH", "HHC-O"],
    alert_id: "1",
  },
  {
    id: "u2",
    type: "warning",
    title: "CBN Under Regulatory Review",
    date: "2026-02-15",
    impact: ["oil", "gummy", "vape"],
    alert_id: "3",
  },
  {
    id: "u3",
    type: "update",
    title: "CBD Import Procedure Changes",
    date: "2026-02-20",
    impact: ["oil", "powder", "cosmetics"],
    alert_id: "5",
  },
];
